### ISSUE TITLE
ADA Poools updates Blocks Lifetime only after epoch end, add current Epoch Blocks to the count

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/www.dolcapool.eu#103]
Hi, please see here, we already have 3 mainnet blocks produced...

![image](https://user-images.githubusercontent.com/18139116/96368226-22e01280-1153-11eb-8672-c0eaa8010d32.png)

@codybutz could you change **Blocks Lifetime** to be a sum of past epoch blocks and current epoch blocks... also please add `attr` element describing we use this method to count Lifetime Blocks...

**Comment by mark-stopka** [comment]
Hi @codybutz, any chance to look at this one over the weekend? I would do it myself, but I am afraid I would miss some corner cases...

**Comment by codybutz** [comment]
See #123 @mark-stopka
