### ISSUE TITLE
bug: Blocks Lifetime shows too high number

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/www.dolcapool.eu#127]
At this point the number should be **4**, not **40**, I suppose it joins 2 strings instead of adding together 2 integers...

![image](https://user-images.githubusercontent.com/18139116/97143718-7b22a000-1763-11eb-9d19-9922a8ffcf6a.png)

Introduced via https://github.com/2nd-Layer/www.dolcapool.eu/pull/123

**Comment by mark-stopka** [comment]
@Sebastix, I am pretty susre your JS skills are good enough to fix this one, would you like to earn some **dCGT** tokens? I value a PR to fix this as metium effort PR (500 tokens if I rememer correctly), although it is low-effrot, as this is a high priority request!

**Comment by mark-stopka** [comment]
Root-cause just confirmed...

![image](https://user-images.githubusercontent.com/18139116/97775798-b9ed9700-1b63-11eb-8872-c13eeec22d7a.png)

**Comment by Sebastix** [comment]
@mark-stopka See merge request https://github.com/2nd-Layer/www.dolcapool.eu/pull/134

**Comment by mark-stopka** [comment]
Fixed by https://github.com/2nd-Layer/www.dolcapool.eu/issues/127

**Comment by mark-stopka** [comment]
![image](https://user-images.githubusercontent.com/18139116/97782494-110a6080-1b92-11eb-910b-6ecc72e1900c.png)
