### ISSUE TITLE
Add DOLCA Stake Pool metadata files

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/www.dolcapool.eu#16]
Please add DOLCA Stake Pool metadata files into [static](https://github.com/2nd-Layer/www.dolcapool.eu/tree/master/src/frontend/static) directory, everything in the `static` directory gets copied as is during the build / release process.

**Comment by mark-stopka** [comment]
@drastys, any update?

**Comment by drastys** [comment]
I will add it soon, maybe will buy some ADA today and change pledge ;-)

**Comment by mark-stopka** [comment]
> I will add it soon, maybe will buy some ADA today and change pledge ;-)

Perfect, round it up to at least 50k, better 75k, I have discussed with others yesterday and we will be able to back you with more stake shortly.

**Comment by drastys** [comment]
My target is currently 50k

**Comment by mark-stopka** [comment]
@drastys can you commit the metadata now?

**Comment by drastys** [comment]
Not possible upload file like JSON so it is changed from json to TXT
[dolca.metadata.txt](https://github.com/2nd-Layer/www.dolcapool.eu/files/5358665/dolca.metadata.txt)
[dolca.extended-metadata.txt](https://github.com/2nd-Layer/www.dolcapool.eu/files/5358666/dolca.extended-metadata.txt)

**Comment by mark-stopka** [comment]
I confirm that the files are now available at:

- https://dolca.2ndlayer.eu/dolca.metadata.json
- https://dolca.2ndlayer.eu/dolca.extended-metadata.json

```
markstopka@ParentsMacBookAir ~ % file dolca.extended-metadata.json 
dolca.extended-metadata.json: JSON data
```

JSON check `curl -L --proto '=https' --tlsv1.2 -sSf https://dolca.2ndlayer.eu/dolca.extended-metadata.json | jq` passes and exits with 0, when there is an error I have encounter error-code 3.
