### ISSUE TITLE
Logo in header

### ISSUE THREAD

**Issue by drastys** [2nd-Layer/www.dolcapool.eu#22]
Maybe it would be nicer, if the logo in header would have only the DOLCApool.eu text without the symbol.

*Original issue*:
> Maybe will be nicer if in header will be only text DOLCApool.eu without circle and square.

**Comment by mark-stopka** [comment]
This is how it looks before and after...

@codybutz what's your opinion on logotype-less header logo? If we want it this way it was resolved by https://github.com/2nd-Layer/www.dolcapool.eu/pull/43 which is currently in master, but we can easily roll-back...

@drastys can you take the screen shot and make a poll in your Czech & Slovak FB Group to drive angagement?

Before:
<img width="1440" alt="Screenshot 2020-10-09 at 15 59 54" src="https://user-images.githubusercontent.com/18139116/95594277-08b77d80-0a4b-11eb-9b76-58c56be7264f.png">

After:
<img width="1440" alt="Screenshot 2020-10-09 at 16 16 02" src="https://user-images.githubusercontent.com/18139116/95594115-cc841d00-0a4a-11eb-90df-42975594df3b.png">

**Comment by mark-stopka** [comment]
@drastys a friend who is an artist stays she likes the new version better, but still plese create the poll so we get the engagement and marketing exposure, give potential delegates a chance to be "part of out pool"...

**Comment by drastys** [comment]
Maybe with logo it looks better in the end ;--) But I will make a poll :-)
