### ISSUE TITLE
Add Our Team page

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/www.dolcapool.eu#29]
@codybutz, @drastys can you please attach a high-resolution photo you would like to be included on **Our Team** page with your profile? We may also consider using something like Bitmoji...

I will use `is-rounded` property to make the pictures circular... 

This page will then be linked from the **Cardano Stake Pool** page in the section about **Governance** as well as from the header menu...

**Comment by mark-stopka** [comment]
My example of Bitmoji created picture few months ago...

![image](https://user-images.githubusercontent.com/18139116/95014466-58f79f80-0647-11eb-8224-049e19a3b5f6.png)

**Comment by Sebastix** [comment]
That's a cool picture @mark-stopka ;)

**Comment by Sebastix** [comment]
Please see this merge request #84

**Comment by codybutz** [comment]
@mark-stopka I added my Bio and image to @Sebastix 's PR :)
