### ISSUE TITLE
Implement Vue.js / Nuxt linter as part of a CI/CD pipeline

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/www.dolcapool.eu#50]
The fact that `nuxt-link` was not closed should be caught up by a CI/CD, the normal build pipeline however did not discover the issue...

I had to fix issue introduced in https://github.com/2nd-Layer/www.dolcapool.eu/pull/48 via https://github.com/2nd-Layer/www.dolcapool.eu/pull/49

**Comment by mark-stopka** [comment]
@codybutz any experience with Vue.js / Nuxt linters you would recommend?

**Comment by Sebastix** [comment]
Eslinter plugin for vuejs? https://eslint.vuejs.org/rules/ 
Where are the CI pipelines processed? I work a lot with Gitlab and I'm not familiar with Github CI.

**Comment by mark-stopka** [comment]
@Sebastix, thanks, I will have a look, the GitHub Action workflows live in https://github.com/2nd-Layer/www.dolcapool.eu/tree/master/.github/workflows

As you can see we have 3 workflows:
- CodeQL security vulnerability scanning
- Front-end build test on branches and pull requests
- Deploy `master` to production

**Comment by codybutz** [comment]
See #86 - you will just have to add `npm run lint` to CI/CD pipeline.
