### ISSUE TITLE
Move JSON API location to package.json or nuxt.config.js

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/www.dolcapool.eu#72]
Hi @codybutz, would it be possible to move JSON API URLs to a single place? I am introducing [Protocol Params](https://js.adapools.org/protocol.json) into the APP also... As part of [**About Cardano page**](https://dolca.2ndlayer.eu/about-cardano/)...

As we grow the amount of API end-points it would be nice to have their location in a single location...

https://github.com/2nd-Layer/www.dolcapool.eu/blob/46e20d62fd96a6d29f16b0bdfd272e9a493107c4/src/frontend/pages/cardano-stake-pool.vue#L151

Also @codybutz, any idea why [these changes](https://github.com/2nd-Layer/www.dolcapool.eu/compare/fetch-params-from-adapools#diff-1bc8e698104fea71f782a90b83dd5970) make the **About Cardano page** not render? No noticeable errors are reported as far as I can see...

**Comment by codybutz** [comment]
@mark-stopka See 79f6ee for fix. `this.protocol` was null therefore it was throwing an error on the page.

**Comment by mark-stopka** [comment]
@codybutz I tried, but it did not provide the correct values (`k = 150` and `a0 = 0.3`, I included dummy values of `k = 250` and `a0 = 0.5` when API code returns `null` in commit 45c254f65357b0bd9e0daca501c8591c2e79cdec.

Can you have a look on how we get the right numbers from ADA Pools API? Once fixed, the correct valued of `150` and `0.3` should appear on the page... 

* [Production](https://dolca.2ndlayer.eu/about-cardano/)
* [Local development](http://localhost:3000/about-cardano/)

**Comment by Sebastix** [comment]
@mark-stopka `resp.data.data` is `undefined` on line 188
Using `resp.data` gives you the right JSON string with all the values

**Comment by Sebastix** [comment]
See commit https://github.com/2nd-Layer/www.dolcapool.eu/pull/79/commits/3e93becc8475ee8bff57c9f7782645eab8c8ed32 for the fix

**Comment by Sebastix** [comment]
As for moving the endpoint links which are used on multiple locations, you need something a global variable list or something. It has been a while I worked with Vuejs, but maybe Vuex will do the trick for this - https://vuex.vuejs.org/guide/
Within NuxtJS: https://nuxtjs.org/guide/vuex-store/
